### ISSUE TITLE
'HSD' object has no attribute 'n_users'

### ISSUE THREAD

**Issue by Kid-Young** [zc-97/HSD#1]
Hello, Thanks for your code. You are not define 'n_users'  attribute to the error that: 
`AttributeError: 'HSD' object has no attribute 'n_users'`

**Comment by zc-97** [comment]
Thanks for your issue : ). In the latest version of RecBole, they canceled the statement of n_users in AbstractRecommender.py. We have fixed it in our project to adapt their update. 

You can get the new HSD and have a try.
